<div class="footer_box">
    <section class="container">
    <nav>
        ©2021 - tous droits réservés au groupe 1 CDA08
        <a href="#">Mentions légales</a>
        l
        <a href="#"> Crédits </a>
        l
        <a href=" index.php?class=admin&action=index">Espace admin</a>
    </nav>
    </section>
</div>
<script src="<?= URL_SOURCE ?>/js/script.js" type="text/javascript"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>