<div class="header_box">
    <section>
        <div>
            <figure class="logo_box">
                <figcaption>HEADER</figcaption>
            </figure>
        </div>
        <div class="nav_box">
            <nav>
                <ul>
                    <li>
                        <a class="<?php echo ($_SERVER['REDIRECT_URL'] == '/findmygaz/home' ? 'button_active' : ' ') ?>" title="home" href="<?= route_to_url('home'); ?>">Accueil</a>
                    </li>
                </ul>
            </nav>
        </div>
    </section>
</div>