<!doctype html>
<html lang="fr">

<head>
    <!-- Required meta tags -->
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Site web</title>
    <meta name="description" content="Description de l'application">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- fontawesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <!--load all styles -->
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" media="screen" type="text/css" href="<?= URL_SOURCE ?>/css/normalize.css" />
    <link rel="stylesheet" media="screen" type="text/css" href="<?= URL_SOURCE ?>/css/style.css" />
</head>

<body>
    <header>
        <?php include "header.phtml" ?>
    </header>
    <main>
        <?php include $app['view'] ?>
    </main>
    <footer>
        <?php include "footer.phtml" ?>
    </footer>
</body>

</html>